name: speedev_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/speedev/speedev_core

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  logger: ^2.5.0
  auto_route: ^10.1.0+1
  firebase_storage: ^12.4.7
  path_provider: ^2.1.5
  firebase_crashlytics: ^4.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5